# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-26 01:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FMItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placement', models.CharField(blank=True, db_column='Placement', max_length=50)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=50)),
                ('logo', models.CharField(blank=True, db_column='Logo', max_length=50)),
                ('line1', models.CharField(blank=True, db_column='Line1', max_length=50)),
                ('line2', models.CharField(blank=True, db_column='Line2', max_length=50)),
                ('line3', models.CharField(blank=True, db_column='Line3', max_length=50)),
                ('line4', models.CharField(blank=True, db_column='Line4', max_length=50)),
                ('line5', models.CharField(blank=True, db_column='Line5', max_length=50)),
                ('type', models.CharField(blank=True, db_column='Type', max_length=50)),
                ('row', models.CharField(blank=True, db_column='Row', max_length=50)),
                ('col', models.CharField(blank=True, db_column='Col', max_length=50)),
                ('paypal_id', models.CharField(blank=True, db_column='PayPal_ID', max_length=50)),
                ('purchaser', models.CharField(blank=True, db_column='Purchaser', max_length=50)),
                ('email', models.CharField(blank=True, db_column='Email', max_length=50)),
                ('install_date', models.DateTimeField(blank=True, db_column='Install_Date')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(blank=True)),
            ],
        ),
    ]
